# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.1.4

pipelines:
  tags:
    release-*:
      - step:
          script:
            - npm install -g bower firebase-tools
            - npm install
            - bower install --allow-root
            - npm run build:prod
            - firebase use --token $FIREBASE_PROD_DEPLOY_TOKEN production
            - firebase deploy -m "Pipeline commit $BITBUCKET_COMMIT" --non-interactive --token $FIREBASE_PROD_DEPLOY_TOKEN
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - npm install -g bower firebase-tools
            - npm install
            - bower install --allow-root
            - npm run build:staging
            - firebase use --token $FIREBASE_DEPLOY_TOKEN default
            - firebase deploy -m "Pipeline commit $BITBUCKET_COMMIT" --non-interactive --token $FIREBASE_DEPLOY_TOKEN
