# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.5.0

pipelines:
  branches:
    feature/firebase-migration:
      - step:
          script: # Modify the commands below to build your repository.
            - npm install -g gulp-cli bower firebase-tools
            - npm install
            - bower install
            - gulp build --stage prod
            - firebase use --token $FIREBASE_DEPLOY_TOKEN default
            - firebase deploy -m "Pipeline commit $BITBUCKET_COMMIT" --non-interactive --token $FIREBASE_DEPLOY_TOKEN
